//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitapSatışPlatformu
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLISHER
    {
        public int PBook_id { get; set; }
        public int Publisher_id { get; set; }
        public string Publisher_name { get; set; }
        public string Translator_name { get; set; }
        public System.DateTime Publishing_date { get; set; }
        public string Language { get; set; }
        public int Num_of_pages { get; set; }
        public int Num_of_pub { get; set; }
        public string Type { get; set; }
        public int Price { get; set; }
    
        public virtual BOOK BOOK { get; set; }
    }
}
